name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    envinronment: test
    steps:
      - name: Run tests
      - uses: actions/checkout@v2
        env:
          COVERAGE: true
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api pytest
    