name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://github.com
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api make test

      - name: Upload coverage data to coveralls.io
        run: docker-compose --file docker-compose.ci.yml run --rm api coveralls --service=github
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
