name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        env:
          COVERAGE: true
          DJANGO_ENV: test
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_REPO_TOKEN:  ${{ secrets.COVERALLS_REPO_TOKEN }}
          repo_token:  ${{ secrets.REPO_TOKEN }}
        run: docker-compose --file docker-compose.ci.yml run --rm api make test

<<<<<<< HEAD
=======
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Pytest
        run: docker-compose --file docker-compose.ci.yml run --rm api make test

>>>>>>> a14a9a8b86a3fc1ea937981522447c3c212724a7
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_REPO_TOKEN:  ${{ secrets.COVERALLS_REPO_TOKEN }}
          repo_token:  ${{ secrets.REPO_TOKEN }}
          parallel: true
          flag-name: Unit Test

  coveralls_finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
