name: Actions_test

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  actions_test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.HIDE_ME }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.HIDE_ME}} | sed 's/./& /g' 
